# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

silent: true

vars:
  DIFY_VERSION: 1.16.0

tasks:
  default:
    cmds:
      - task --list

  init:
    aliases: [i]
    desc: Init
    dir: '{{.USER_WORKING_DIR}}/versions/{{.DIFY_VERSION}}'
    cmds:
      - pwd
      - ln -s ../../_init.sh _init.sh
      - uncmnt .env.example > .env
      - sed -i "" -e "s/^LANG=en_US.UTF-8$/LANG=ja_JP.UTF-8/g" .env
      - sed -i "" -e "s/^LC_ALL=en_US.UTF-8$/LC_ALL=ja_JP.UTF-8/g" .env
      - sed -i "" -e "s/^LOG_TZ=UTC$/LOG_TZ=Asia\/Tokyo/g" .env
      - sed -i "" -e "s/^VECTOR_STORE=weaviate$/VECTOR_STORE=qdrant/g" .env
      - sed -i "" -e "s/^FORCE_VERIFYING_SIGNATURE=true$/FORCE_VERIFYING_SIGNATURE=false/g" .env
